name: CI with Cache
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: prime-cache-408c663
      id: cache-step
      uses: actions/cache@v4
      with:
        key: cache-408c663
        path: ~/.cache
    - name: Show cache result
      run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
